on: 
  push:
     tags:
      - "certi-static*"

name: 🚀 Deploy website on push


jobs:
  web-deploy:
    env:
      VITE_MASTER_TOKEN: ${{ vars.HASURA_SECRET }}
      VITE_GRAPHQL_URL: ${{ vars.HASURA_BASE_URLs }}
      VITE_IS_HASH_PROVIDER: true
      VITE_WOOPRA_DOMAIN: ${{ vars.WOOPRA_DOMAIN }}
      VITE_ABLY_TOKEN: ${{ vars.ABLY_TOKEN }}
    name: 🎉 Deploy Web
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - name: Build
      working-directory: apps/web-csr
      run: |
        pnpm install
        pnpm build
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        log-level: verbose
        local-dir: ./apps/web-csr/dist/
        server-dir: public_html/
